### ISSUE TITLE
Добавить редайрект на главную страничку (юзер страница) со страницы с оценками

### ISSUE THREAD

**Issue by mmargullan** [mmargullan/rk-frontend#15]
Алишер прочти документацию vue/vuetify и отпишись какое решение можно использовать (простая кнопка, навбар, ссылка для редайректа). Также надо уже отправлять запрос на бэк чтобы вытаскивать данные о оценках

**Comment by K4444R** [comment]
Отправил Pull request 
https://github.com/mmargullan/rk-frontend/pull/17

**Comment by K4444R** [comment]
https://github.com/mmargullan/rk-frontend/pull/18

добавил редайрект
