### ISSUE TITLE
Обновление главной страницы

### ISSUE THREAD

**Issue by mmargullan** [mmargullan/rk-frontend#16]
Надо сделать главную страницу более живой, добавить каких то анимаций на задний фон. Также страница выглядит пустой, надо изменить структуру карточки с данными юзера и/или добавить еще каких то фич

**Comment by mmargullan** [comment]
Еще предлагаю вместо факультета (их в там 2 в универе) написать специальность (у нас например программная инженерия)

**Comment by K4444R** [comment]
Предлагаю переключаться между оценками (между курсами и семестрами)

**Comment by mmargullan** [comment]
Тогда структуру запроса надо менять, это на потом оставим - нам надо завтра уже сдавать джаву

**Comment by K4444R** [comment]
https://github.com/mmargullan/rk-frontend/pull/21

Запарсил данные пока
