### ISSUE TITLE
Новый функционал/страницы

### ISSUE THREAD

**Issue by mmargullan** [mmargullan/rk-frontend#32]
Как смотрите на то чтобы добавить велком страницу для приложения, потому что вход сразу как то угрюмо выглядит. Также можете предлагать идеи для нового функционала приложения

**Comment by K4444R** [comment]
Можно 

Тогда на навбаре справо нужно добавить логин кнопку

**Comment by mmargullan** [comment]
Скорее отдельная страница которая не привязана к платонусу а просто как проджект овервью
