### ISSUE TITLE
Изменения в запросах - JWT

### ISSUE THREAD

**Issue by mmargullan** [mmargullan/rk-frontend#34]
Ребята нас ждет большое изменения в клиентской стороне, теперь мы должны в заголовке каждого запроса передавать JWT токен, это нужно для того, чтобы в сети каждый запрос шел защищенным и не конфликтовал с другими запросами. В общем для того чтобы получить токен надо авторизоваться как обычно, и сохранить на фронтенде токен либо с заголовка запроса либо с тела. Пока что придумайте как вытащить его с заголовка и хранить

**Comment by K4444R** [comment]
https://github.com/mmargullan/rk-frontend/pull/35
